### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by yossi-idt** [ewendlick/git-commit-info-webpack-plugin#2]
I added this package to my Vue 2 project. It generates the file with the correct data and puts it exactly where it needs to go, but when I import that file into a component (or store), my compiler goes haywire and just goes into what looks like an infinite reloading loop

**Comment by ewendlick** [comment]
Hello @yossi-idt ,

Depending on how Webpack is set up, you may need to change `afterEmit` to something else. (maybe `emit`?) https://webpack.js.org/api/compiler-hooks/
If you make these changes, it would be best just to vendor in this NPM package.
Please let me know if this works for you. :bow:

**Comment by yossi-idt** [comment]
Thank you
